sudo: required
services:
- docker
language: cpp
before_install: docker build --build-arg external_username=$(id --user --name) --build-arg
  external_uid=$(id --user) --build-arg external_gid=$(id --group) -t pikmin-nds .
script: docker run -i --rm -v $(pwd):/source pikmin-nds
before_deploy:
- mkdir release
- mv pikmin-nds.nds release/pikmin-$(date +%F)-$(git rev-parse --verify --short HEAD).nds
- cd release
deploy:
  provider: cloudfiles
  username: zeta0134
  api-key:
    secure: l49Bv4uvNxDmSebXuzACFD2Ftwe7d3nxfYZe308Tt0ffYXhN1xDhyMC3533EL0O2K358XRGKIbeYmwTwcRH6laFWEoSyquiYWm+B5JAnP4uE2mdUF0HLf/Zj8NLJtz9NQZOY+OXKQT1x4mcbfe0fH/5Ros2c5Oo4tuT7uBWj9Q1i20/ZWJZdmjI/qpi21c4CEqKXxBjSKz2WWF4ILkIgelnUIlgACj4+keMPeE29GBB2dKkotPo6Ige6T4ZacTpKXLWKDxK/jynPO9SEWCBv4ecboiZfoYgvGTWVAYoCnJztQ+iW3lj6Nl1qb+FwWETdKHM06lp29DBnQ9O6YCZL7axC3w8xMQURgnGM4//kRVurxQVOD0u7OxgrGX3Zi4NdJJE+SjKGWkw3fSATckZcnjAZ5PaLIj5mwtwjNGlgN3QZV0mP/YhTYJOleo7lGmxGLA7XVHW5UyWbASEGoi0b7qtxH743jHa4WrDRR/JfJI/L3VZz3lw09W5rqh1sDw9Y022SDjpAJp7ypdNCMUT9Is+tkufsJhn2PrrO+ZxRI57nqbCLHquy7uhWs7SZodYI42sYhTbd2bU95jArV2I4Yw6LpJwOwIxqdtDdGzgI4cv1wikrUaFTqou20U0iYJyxcu4sdT19/jwM31sPJ3iYFO/Qjc1M0GnVIS4gsUbddIw=
  region: DFW
  container: pikminds-builds
  on:
    repo: zeta0134/pikmin-nds
  skip_cleanup: true
