sudo: required

services:
- docker

language: cpp

before_install: docker build --build-arg external_username=$(id --user --name) --build-arg
  external_uid=$(id --user) --build-arg external_gid=$(id --group) -t pikmin-nds .

script: docker run -i --rm -v $(pwd):/source pikmin-nds

before_deploy:
  mkdir release
  mv pikmin-nds.nds release/pikmin.nds
  cd release

deploy:
  provider: cloudfiles
  username: zeta0134
  api_key:
    secure: E8cDJYciblEggIETOGnZ6yY4KVzxMzuezoR18+4sUJ1VA4SR8vwrcVCtNYcIyNWytfhT0bJPmY2tMVKE5FyBRHl+K0ibDY5rVnlDbhawVJ9vbp+/qkMbrpiujBxkbRJZEBlkVNMSSrYooad93/zp8PK7Ng1GNnFnNZb4Xt8Di5IQzYrdgVIVmmoRCnzRcL6lG4q+xZxHUDP6huyr5/oAuUuoIkqODW75WgnIea4Ob8xoZb/sz/7QejQSCxTUtdLQK71JrI5upXB9vuJoHccrtG6uf2+voA+SjDNeRTSzWDysBgOBWee5ILJSSWZDLh42zaAVwZqqPovXoT/NSCS6XMoCPMqDAmmGFAQt1bBujz2Qz6rErxfZ57A2T6jg+lySXKNngCJvBLYqhgKUEOLW6jym9BI1irQ+WsRZCcbXIPYHgRQ/VfAoNOASpFKC+sYE+L2yNfiJEFQekMPrQuu6A+j46P3WUpzNC9pVsufcNMCX3Z2ZDBhXpuSfCg/53MW2UlRixIw0PVCaWbabs5y9tHpDi3BGGfsnyNhKyJV7UG6Ti1oSSLV+u7bnl5ajq5+Be48tETa8MhrkCu4mmRRU7zNSvnfowi+0fogsdiCAbK+vUOah3vvOvkbM8McWMagBV0Wuvz4u9RsgxknQ+0CYW8EVaVo8kBMpKr2icSfZPHI=
  region: DFW
  container: pikminds-builds
  on:
    repo: zeta0134/pikmin-nds
  skip_cleanup: true
