sudo: required
services:
- docker
language: cpp
before_install: docker build --build-arg external_username=$(id --user --name) --build-arg
  external_uid=$(id --user) --build-arg external_gid=$(id --group) -t pikmin-nds .
script: docker run -i --rm -v $(pwd):/source pikmin-nds
before_deploy:
- mkdir release
- mv pikmin-nds.nds release/pikmin-$(date +%F)-$(git rev-parse --verify --short HEAD).nds
- cd release
deploy:
  provider: cloudfiles
  username: zeta0134
  api-key:
    secure: "RXtF7LiEDTQ0eb1N9IdzW4pcXHkgrdeGjyXHzFHtO6QFUxh4uoZAbAKAELgvT9ylPDJEFOdKuPt25l0PixUh6k82jmu6pyuwnmrlIyrTbCsCmpx1hpIVWV823GQx7Cg1y1Ykvklw62db1BYPdwZTJHRJyVc3AIgFwxrhfJr4Pdsnsz4QS14bLZFzZ3vaoADwAMS1X3qUi18hhQEQ35dBF6SfPBRLNilPQS25Cj7ejWLczQkstiEPKgsZzXe06e8fC6zFa4ffUVUJ3uXkpUhBHUqoVyNFVNoii3M2dfHwenfGu/NxmMxez2nzPuJnrob2ynNv9Cz74iAdcPoFb2gLe8ytRfxWyAuxY20HSfs9509qOpCWHCh0cgDzwS3kLsmzNAFt/mshlzaMN10Ek46gU1iRfiQQSddoB/yGfHQM98JtLB7RbVHAdOng1qdRwsul2TZjuUj5RNcrE89+KZAMF1flScKR/Vh0wW1ihjyKRb7+6t7es0slFwV6lec3lMPFovWpb7S28QDDeEw1HPDnCqhgEmPX+0MU9P3OtoGW93qjw3UBB5gtLb3ISnj0C2IbUAaCNOcxWRBmBF65l516SbvSsSsOko3pZMxel8ppx2SBNg7plDgzNdf6agdEGS8qL0HDI5TB4qWgMX6vQn1cVNpATrloK28rpmA6pkYt49k="
  region: DFW
  container: pikminds-builds
  on:
    repo: zeta0134/pikmin-nds
  skip_cleanup: true
