#include "sfx.h"
#include "soundbank.h" // Generated by MaxMod

#include <cstdlib> // rand()

using numeric_types::fixed;
using numeric_types::literals::operator"" _f;

const sfx::Effect effects[sfx::kTotal] {
	{SFX_FOOTSTEP_HARD, 0.15_f},
};

fixed random_variation() {
	// Returns a random fixed number from -1.0_f - 0.99_f
	return fixed::FromRaw((rand() & 0x1FFF) - 0x1000);
}

void sfx::PlaySound(int effect_id) {
	fixed pitch = 1.0_f + (random_variation() * effects[effect_id].pitch_variation);

	mm_sound_effect footstep = {
      { effects[effect_id].sample_id } ,      // id
      (mm_hword)(pitch.data_ >> 2),  // rate
      0,    // handle
      255,  // volume
      127,  // panning
  };
  mmEffectEx(&footstep);
}
